---
abstract: 'Parse cpanfile for prereqs'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Dist::Zilla::Plugin::Prereqs::FromCPANfile
name: Dist-Zilla-Plugin-Prereqs-FromCPANfile
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Dist::Zilla::Plugin::Prereqs::FromCPANfile:
    file: lib/Dist/Zilla/Plugin/Prereqs/FromCPANfile.pm
    version: 0.01
requires:
  Dist::Zilla: 4
  Module::CPANfile: 0.901
  Try::Tiny: 0.1
resources:
  bugtracker: https://github.com/miyagawa/Dist-Zilla-Plugin-Prereqs-FromCPANfile/issues
  homepage: https://github.com/miyagawa/Dist-Zilla-Plugin-Prereqs-FromCPANfile
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Dist-Zilla-Plugin-Prereqs-FromCPANfile.git
version: 0.01
